#cloud-config
package_upgrade: true

packages:
  - git
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker azureuser

  - git clone https://github.com/SerhiiKysil/docker_lab.git /home/azureuser/docker_lab
  - chown -R azureuser:azureuser /home/azureuser/docker_lab


  - docker network create labor_network || true
  - cd /home/azureuser/docker_lab
  - docker compose -f compose.yml up --build -d
  - cd /home/azureuser/docker_lab/monitoring
  - docker compose -f docker-compose.monitoring.yml up -d