apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-lab-web
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SerhiiKysil/docker_lab.git
    targetRevision: main
    path: gitops/app

  destination:
    server: https://kubernetes.default.svc
    namespace: docker-lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true