apiVersion: v1
kind: Service
metadata:
  name: docker-lab-web-service
  namespace: docker-lab
spec:
  type: NodePort
  selector:
    app: docker-lab-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080